### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by isarker** [Orpine/py-R-FCN#19]
4.Since py-faster-rcnn does not support multiple training datasets, we need to merge VOC 2007 data and VOC 2012 data manually. Just make a new directory named VOC0712, put all subfolders except ImageSets in VOC2007 and VOC2012 into VOC0712(you'll merge some folders). **I provide a merged-version ImageSets** folder for you, please put it into VOCdevkit/VOC0712/.
when i follow this step and marged with provided Imageset than i got  this error

 'USE_GPU_NMS': True}
Loaded dataset `voc_0712_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_0712_trainval gt roidb loaded from /home/user01/Music/fc/py-R-FCN/data/cache/voc_0712_trainval_gt_roidb.pkl
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 66, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/user01/Music/fc/py-R-FCN/tools/../lib/fast_rcnn/train.py", line 142, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/user01/Music/fc/py-R-FCN/tools/../lib/datasets/imdb.py", line 111, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError

but if i use the Imageset from VOC2007 than got this error,does anyone face same problem?

im_detect: 4948/4952 0.097s 0.001s
im_detect: 4949/4952 0.097s 0.001s
im_detect: 4950/4952 0.097s 0.001s
im_detect: 4951/4952 0.097s 0.001s
im_detect: 4952/4952 0.097s 0.001s
Evaluating detections
Writing aeroplane VOC results file
Traceback (most recent call last):
  File "./tools/test_net.py", line 90, in <module>
    test_net(net, imdb, max_per_image=args.max_per_image, vis=args.vis)
  File "/home/user01/Music/fc/py-R-FCN/tools/../lib/fast_rcnn/test.py", line 298, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/user01/Music/fc/py-R-FCN/tools/../lib/datasets/pascal_voc.py", line 321, in evaluate_detections
    self._write_voc_results_file(all_boxes)
  File "/home/user01/Music/fc/py-R-FCN/tools/../lib/datasets/pascal_voc.py", line 248, in _write_voc_results_file
    with open(filename, 'wt') as f:
IOError: [Errno 2] No such file or directory: '/home/user01/Music/fc/py-R-FCN/data/VOCdevkit0712/results/VOC0712/Main/comp4_33830d8c-2942-4517-b6ca-6a2beeaa1c62_det_test_aeroplane.txt'

**Comment by matakk** [comment]
I have the same error, I just mkdir -p /home/user01/Music/fc/py-R-FCN/data/VOCdevkit0712/results/VOC0712/Main/ ,and retrain .

**Comment by macqueen09** [comment]
same question , and I fond that I change my PascalVOC2007 to PascalVOC0712 and I forget to change "/home/user01/Music/fc/py-R-FCN/data/VOCdevkit2007" to "VOCdeviket0712". now I'm retest again. (we needn't to retrain)
