### ISSUE TITLE
AssertionError when running end to end training

### ISSUE THREAD

**Issue by SeaOfOcean** [Orpine/py-R-FCN#6]
Hi I met a problem when running end to end training with pascal dataset.

Traceback (most recent call last):
  File "./tools/train_net.py", line 107, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 70, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 67, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/test/xianyan/py-R-FCN/tools/../lib/fast_rcnn/train.py", line 142, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/test/xianyan/py-R-FCN/tools/../lib/datasets/imdb.py", line 111, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError

**Comment by Orpine** [comment]
The code will check if the boxes are illegal after flipping images. I suggest you to printing the boxes and image widths to see whether you load gt boxes and read image info correctly.

**Comment by Orpine** [comment]
Closing due to inactivity. Feel free to reopen.
