### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wjwstate** [Orpine/py-R-FCN#93]
when use ./experiments/scripts/rfcn_end2end_ohem.sh 0 ResNet-50 pascal_voc
get the error 
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 62, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/wujianwen/files/py-R-FCN/tools/../lib/datasets/factory.py", line 39, in get_imdb
    return __sets[name]()
  File "/home/wujianwen/files/py-R-FCN/tools/../lib/datasets/factory.py", line 20, in <lambda>
    __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
  File "/home/wujianwen/files/py-R-FCN/tools/../lib/datasets/pascal_voc.py", line 38, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/wujianwen/files/py-R-FCN/tools/../lib/datasets/pascal_voc.py", line 82, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: /home/wujianwen/files/py-R-FCN/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt

**Comment by unicoe** [comment]
@wjwstate 
You should check your path "/home/wujianwen/files/py-R-FCN/data/VOCdevkit2007/VOC2007/ImageSets/Main/trainval.txt", the path could is error.
